### ISSUE TITLE
Cannot find new_config_file.config after running rnn_sample

### ISSUE THREAD

**Issue by sakares** [llSourcell/AI_Composer#2]
Hi,

After I ran the training for hour and found a message like 

```
Epoch: 29, Train Loss: 0.547316406171, Time Per Epoch: 146.813248034
Valid Loss: 0.572111875409
Best loss so far encountered, saving model.
```
According to README, I think I can stop running training and started to generate new MIDI song but after I ran the command for generating. it turned out that they can't find the given config file.

Did I miss any steps? please suggest.

Thanks!

**Comment by tigerneil** [comment]
You can find the config in this directory or something like the name 
@sakares 

```
> $ python rnn_sample.py --config_file models/0524_1815/nl_2_hs_200_mc_0p5_dp_0p5_idp_0p8_tb_128.config         ⬡ 5.9.1 [±master ✓]
```
Good luck!

**Comment by sakares** [comment]
@tigerneil Awesome, finally, I got the beautiful MIDI!
