### ISSUE TITLE
Enhancement - Tensorflow Dockerfile

### ISSUE THREAD

**Issue by johndpope** [llSourcell/AI_Composer#8]
it's possible to use this base image as a container for your program
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker

eg. 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.devel

or you can cherry pick my scripts here ->
https://github.com/johndpope/DockerParseyMcParsefaceAPI/blob/master/docker/dsparseyapi/Dockerfile

once you get a gist that you can run - update dockerfile to fetch gist and run it.

this will resolve all the other issues and speed up getting environment up and running.
eg. https://github.com/johndpope/DockerParseyMcParsefaceAPI
should be able to run 
**make start**

and entire parsey mcparseface should download and build.

**Comment by llSourcell** [comment]
can you make a PR for this? i would greatly appreciate it :)

**Comment by johndpope** [comment]
there is an official magenta docker file (although some bugs)
https://github.com/tensorflow/magenta/blob/master/magenta/tools/docker/Dockerfile

I recreated it.
https://gist.github.com/johndpope/2d3a90c8d70b22732ad75b6ebec60187

Probably would benefit you to use  a base image going forward with your tutorials.

**Comment by johndpope** [comment]
closing out old issues.
