### ISSUE TITLE
Training is 'killed' prematurely on Linux

### ISSUE THREAD

**Issue by ayeshabasit** [llSourcell/AI_Composer#9]
<img width="447" alt="capture" src="https://cloud.githubusercontent.com/assets/23487380/20326071/015f3ad2-aba9-11e6-8114-5f58b187e4ba.PNG">

So right after the message about the delay etc, the process stops priniting anything and remains idle then its killed suddenly - any idea why this is happening or how to fix it?

**Comment by 0xdwang** [comment]
Did you figure out a solution? This is happening to me too

**Comment by ayeshabasit** [comment]
Yeah I did, I was doing it on virtual box which has like very little memory so I moved to a 4 gig computer which started training but would kill the process in about 4 hours, so then I moved to a 32 GB Ubuntu system and training would complete half an hour on there. So basically, it was because of not enough memory.
